trigger:
- master
- candidate*
- release*
- development*
- arcane_dev*

pr:
- master

variables:
  rack-sdk-version: 1.1.6

  add-gitrev-to-plugin-version: |
    gitrev=`git rev-parse --short HEAD`
    version="1.0.${gitrev}"
    echo "Updating to version=$version"
    tf=`mktemp`
    jq --arg VERSION "$version" '.version=$VERSION' plugin.json > $tf
    mv $tf plugin.json
  add-release-notes: |
    cat <<- EOH
    # Aria Salvatrice Signature Series development builds
    These test builds are produced on every commit. Expect crashes and half-finished modules! If you just want to install my modules, install them from the official VCV Library instead.
    EOH
    date
    echo ""
    echo "Most recent commits:"
    echo ""
    git log --pretty=oneline | head -5
stages:
- stage: build
  displayName: Build Plugin
  jobs:
  - job: BuildPlugin
    strategy:
      matrix:
        Mac:
          imageName: macos-10.14
          prepare-env: ""
          artifact: Plugin-MacOS
        Windows:
          imageName: vs2017-win2016
          prepare-env: C:/msys64/usr/bin/pacman -S --noconfirm zip unzip && export CC=gcc
          artifact: Plugin-Windows
        Linux:
          imageName: ubuntu-16.04
          prepare-env: sudo apt install -y libglu-dev
          artifact: Plugin-Linux

    pool:
      vmImage: $(imageName)

    steps:
    - checkout: self
      fetchDepth: 1
    - bash: |
        uname -a
        git submodule update --init --recursive
        pushd $AGENT_TEMPDIRECTORY
        curl -o Rack-SDK.zip https://vcvrack.com/downloads/Rack-SDK-$(rack-sdk-version).zip
        unzip Rack-SDK.zip
      displayName: Get Rack-SDK
    - bash: |
        $(add-gitrev-to-plugin-version)
      displayName: Update Version in plugins.json
    - bash: |
        $(prepare-env)
        export RACK_DIR=$AGENT_TEMPDIRECTORY/Rack-SDK
        make dep
        make dist
        mkdir artifact
        cp dist/*.zip artifact/
      displayName: Build Plugin
    - task: PublishPipelineArtifact@1
      inputs:
        path: $(System.DefaultWorkingDirectory)/artifact
        artifact: $(artifact)

- stage: publish
  displayName: Publish Plugin
  dependsOn: build
  jobs:
    - job: PublishArtifacts
      steps:
        - task: DownloadPipelineArtifact@2
          inputs:
            artifact: Plugin-Linux
            patterns: "**/*.zip"
            targetPath: $(Build.ArtifactStagingDirectory)
        - task: DownloadPipelineArtifact@2
          inputs:
            artifact: Plugin-MacOS
            patterns: "**/*.zip"
            targetPath: $(Build.ArtifactStagingDirectory)
        - task: DownloadPipelineArtifact@2
          inputs:
            artifact: Plugin-Windows
            patterns: "**/*.zip"
            targetPath: $(Build.ArtifactStagingDirectory)
        - bash: |
            ls -l $(Build.ArtifactStagingDirectory)
            export EXTEND_TAG=`date "+%Y%m%d"`
            for file in $(Build.ArtifactStagingDirectory)/*.zip; do mv "$file" "${file/.zip/-${EXTEND_TAG}.zip}"; done
            ls -l $(Build.ArtifactStagingDirectory)
          displayName: Tag asset names with Date
        - bash: |
            $(add-release-notes) > $(Build.ArtifactStagingDirectory)/ReleaseNotes.md
          displayName: Add release notes
        - task: GitHubRelease@0
          condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/development'))
          displayName: "Update Github Release"
          inputs:
            gitHubConnection: github.com_AriaSalvatrice
            repositoryName: AriaSalvatrice/AriaVCVModules
            action: edit
            tag: AzureCI
            target: '$(Build.SourceVersion)'
            addChangeLog: false
            releaseNotesFile: $(Build.ArtifactStagingDirectory)/ReleaseNotes.md
            assets: $(Build.ArtifactStagingDirectory)/*.zip
